Website/Models/ErrorViewModel.cs
using System;

namespace Website.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Website/Controllers/AutomationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Website.Controllers
{
    public class AutomationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Development()
        {
            return View();
        }

        public IActionResult Deployment()
        {
            return View();
        }

        public IActionResult Test()
        {
            return View();
        }

        public IActionResult Analytics()
        {
            return View();
        }
    }
}

Website/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Website.Models;

namespace Website.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Website/Views/Automation/Analytics.cshtml
@{
    ViewData["Title"] = "Analytics";
}

<h2>Analytics</h2>

Website/Views/Automation/Deployment.cshtml
@{
    ViewData["Title"] = "Deployment";
}

<h2>Deployment</h2>

Website/Views/Automation/Development.cshtml
@{
    ViewData["Title"] = "Development";
}

<h2>Development</h2>

Website/Views/Automation/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

Website/Views/Automation/Test.cshtml
@{
    ViewData["Title"] = "Test";
}

<h2>Test</h2>

Website/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Website/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Website/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row center">
    <h2><b>THE FUTURE IS AUTOMATED</b></h2>
</div>

<div class="row">
    <div class="col s12 m6">
        <div class="card blue-grey lighten-5 ">
            <div class="card-content ">
                <span class="card-title"><b>Development Automation</b></span>
                <hr />
                <p>
                    Feature branch and release builds on code changes with integrated unit testing through pipelines.
                </p>

            </div>
            <div class="card-action">
                <a asp-controller="Automation" asp-action="Development">Read more...</a>
            </div>
        </div>
    </div>
    <div class="col s12 m6">
        <div class="card blue-grey lighten-5 ">
            <div class="card-content ">
                <span class="card-title"><b>Deployment Automation</b></span>
                <hr />
                <p>
                    Dynamic environment management, configuration and installation using containers.
                </p>

            </div>
            <div class="card-action">
                <a asp-controller="Automation" asp-action="Deployment">Read more...</a>
            </div>
        </div>
    </div>
    <div class="col s12 m6">
        <div class="card blue-grey lighten-5 ">
            <div class="card-content ">
                <span class="card-title"><b>Test Automation</b></span>
                <hr />
                <p>
                    Behavior driven API and cross-browser and cross-platform web testing.
                </p>

            </div>
            <div class="card-action">
                <a asp-controller="Automation" asp-action="Test">Read more...</a>
            </div>
        </div>
    </div>
    <div class="col s12 m6">
        <div class="card blue-grey lighten-5 ">
            <div class="card-content ">
                <span class="card-title"><b>Analytics Automation</b></span>
                <hr />
                <p>
                    Continuous monitoring of availabiliy and performance in development and production.
                </p>

            </div>
            <div class="card-action">
                <a asp-controller="Automation" asp-action="Analytics">Read more...</a>
            </div>
        </div>
    </div>
</div>

Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Website</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/materialize/css/materialize.css" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" asp-fallback-href="~/fonts/material-icons/materialicons.css" rel="stylesheet" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" asp-fallback-href="~/fonts/material-icons/materialicons.css" rel="stylesheet" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @*<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Website</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>*@

@*<partial name="_CookieConsentPartial" />*@

<nav>
    <div class="container">
        <div class="nav-wrapper">
            <div style="width: 10% ; transform: translateY(7px); display: inline-grid">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 514.41 196.65">
                    <defs>
                        <style type="text/css">
                            .cls-1 {
                                fill: #414042;
                            }

                            .cls-2-nav {
                                fill: white;
                            }
                        </style>
                    </defs>
                    <title>UnikieLogo_2018</title>
                    <g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M451,178.27l63.71,0c-6.23,5.89-15,12.7-21.59,18.36H422.07c0-21.71-.09-47-.09-67.37h71.94s14.38,13.46,19.48,17.77H451Z" transform="translate(-0.3)"></path><path class="cls-1" d="M456.6,157.05h39.57c-5.41,4.5-7.82,6.52-14.06,11.81H456.6Z" transform="translate(-0.3)"></path><path class="cls-1" d="M408,129.28v67.37h-28.9V129.28Z" transform="translate(-0.3)"></path><path class="cls-1" d="M373.83,196.65h-34.3s-15.71-12.91-19.8-16.52c-6.13-5.37-11.54-10.8-16.76-15V149.53c7.45-7,15.13-13.55,22.81-20.2h34c-10.54,9.58-20.62,18.48-31.2,27.37C343.12,169.77,373.83,196.65,373.83,196.65Z" transform="translate(-0.3)"></path><path class="cls-1" d="M297.63,114.82v81.83h-28.9v-79.4c0-1.4,0-2.43,0-2.43Z" transform="translate(-0.3)"></path><path class="cls-1" d="M254.55,114.82v81.83H225.69c-.06-26.71-.06-56.61-.06-81.83Z" transform="translate(-0.3)"></path><path class="cls-1" d="M91.9,183.8v12.85h-80C6.63,196.65.36,192.36.36,185.4c0-9.82-.06-22.35-.06-34.7s0-24.53,0-35.88H29.23v60.61h34c0-9.44.08-19.19,0-29.38s-.21-21.42-.06-31.23H91.9S91.9,183.76,91.9,183.8Z" transform="translate(-0.3)"></path><polygon class="cls-1" points="173.08 0 194.97 31.56 142.29 100.39 95.86 100.39 133.94 50.88 173.08 0"></polygon><path class="cls-2-nav" d="M243.41,100.39,222.14,69.77,199.35,37.43l-24,31.46-24,31.46,32.62,0v62.76c-6.19-6-19.69-21.32-27-29.23-11.6-12.62-14.93-19.08-34.56-19.08-10.66,0-17.44,6.3-17.44,14.24v67.58h28.48V149.75c9,9.84,11,11.58,19,20.36a239.92,239.92,0,0,0,18.27,18.53c4.68,4.29,10.64,8,20,8,11.07,0,21.73-2.88,21.73-13.39,0-18.7,0-63.42,0-82.87Z"></path></g></g>
                </svg>
            </div>
            <a class="brand-logo center" asp-area="" asp-controller="Home" asp-action="Index" class="brand-logo">Software Quality Assurance</a>
            @*<ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
            </ul>*@
        </div>
    </div>
</nav>

<div id="loader-container" class="preloader-background">
    <div id="" class="row center">
        <div style="transform: translateX(10%) translateY(15%);">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 514.41 196.65">
                <defs>
                    <style type="text/css">
                        .cls-1 {
                            fill: #414042;
                        }

                        .cls-2 {
                            fill: #27aae1;
                        }
                    </style>
                </defs>
                <title>UnikieLogo_2018</title>
                <g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M451,178.27l63.71,0c-6.23,5.89-15,12.7-21.59,18.36H422.07c0-21.71-.09-47-.09-67.37h71.94s14.38,13.46,19.48,17.77H451Z" transform="translate(-0.3)"></path><path class="cls-1" d="M456.6,157.05h39.57c-5.41,4.5-7.82,6.52-14.06,11.81H456.6Z" transform="translate(-0.3)"></path><path class="cls-1" d="M408,129.28v67.37h-28.9V129.28Z" transform="translate(-0.3)"></path><path class="cls-1" d="M373.83,196.65h-34.3s-15.71-12.91-19.8-16.52c-6.13-5.37-11.54-10.8-16.76-15V149.53c7.45-7,15.13-13.55,22.81-20.2h34c-10.54,9.58-20.62,18.48-31.2,27.37C343.12,169.77,373.83,196.65,373.83,196.65Z" transform="translate(-0.3)"></path><path class="cls-1" d="M297.63,114.82v81.83h-28.9v-79.4c0-1.4,0-2.43,0-2.43Z" transform="translate(-0.3)"></path><path class="cls-1" d="M254.55,114.82v81.83H225.69c-.06-26.71-.06-56.61-.06-81.83Z" transform="translate(-0.3)"></path><path class="cls-1" d="M91.9,183.8v12.85h-80C6.63,196.65.36,192.36.36,185.4c0-9.82-.06-22.35-.06-34.7s0-24.53,0-35.88H29.23v60.61h34c0-9.44.08-19.19,0-29.38s-.21-21.42-.06-31.23H91.9S91.9,183.76,91.9,183.8Z" transform="translate(-0.3)"></path><polygon class="cls-1" points="173.08 0 194.97 31.56 142.29 100.39 95.86 100.39 133.94 50.88 173.08 0"></polygon><path class="cls-2" d="M243.41,100.39,222.14,69.77,199.35,37.43l-24,31.46-24,31.46,32.62,0v62.76c-6.19-6-19.69-21.32-27-29.23-11.6-12.62-14.93-19.08-34.56-19.08-10.66,0-17.44,6.3-17.44,14.24v67.58h28.48V149.75c9,9.84,11,11.58,19,20.36a239.92,239.92,0,0,0,18.27,18.53c4.68,4.29,10.64,8,20,8,11.07,0,21.73-2.88,21.73-13.39,0-18.7,0-63.42,0-82.87Z"></path></g></g>
            </svg>
        </div>
        <div id="loader">

        </div>
    </div>
</div>

<div id="content" class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Website</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/materialize/js/materialize.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>